"""github collection fields

Revision ID: 787b429d5d42
Revises: fba098a68810
Create Date: 2026-08-09 17:30:19.312740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '787b429d5d42'
down_revision: Union[str, None] = 'fba098a68810'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('github_connected_by_user_id', sa.UUID(), nullable=True))
    op.add_column('projects', sa.Column('gh_last_collected_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('projects', sa.Column('gh_last_error', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('simulated_now', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'projects', 'users', ['github_connected_by_user_id'], ['id'])
    op.create_unique_constraint('uq_raw_event_project_type_github_id', 'raw_events', ['project_id', 'type', 'github_id'])
    op.add_column('users', sa.Column('github_access_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'github_access_token')
    op.drop_constraint('uq_raw_event_project_type_github_id', 'raw_events', type_='unique')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'simulated_now')
    op.drop_column('projects', 'gh_last_error')
    op.drop_column('projects', 'gh_last_collected_at')
    op.drop_column('projects', 'github_connected_by_user_id')
    # ### end Alembic commands ###
